### PR TITLE
Upgrade ember

### PR DESCRIPTION
**Pull request by lowski**
Hey @qoobaa,
I've been using fakturama for issuing invoices for more than 2 years. It's really great app!

Recently I've been trying to migrate the project to use ember-cli the upgrade Ember version (`2.15` when I started the process). Because the project was quite old I encountered some issues that I had to solve one way or another (i.e. use single HTML as entry point instead of the two: `app.html` and `index.html`).

I'm creating this PR as a staring point. Some of the things could definitely be improved (validation could be switched to `ember-cp-validation` or `ember-changeset`, code coverage could be higher, custom ember-data adapter could be replaced with official one, etc.) but I didn't want to improve all things at once. My goal was to be able to run the project on Ember 2.1x with ember-cli.

Syntax could also be migrated to ES6 - I run [codemod](https://github.com/ember-cli/ember-modules-codemod) but it didn't pick-up everything.

Please check it if when you have a moment and let me know what you think.

### CODE REVIEW

**Comment by qoobaa** [comment]
Hey,

I've been thinking about upgrading the project to use the Ember CLI for a long time, but I didn't actually have enough time to do it. This looks like a great starting point, I'll take a look at it soon. Thank you very much for your help, I really appreciate it :-).

Cheers.

**Comment by qoobaa** [comment]
I'm trying to test your branch and I have some issues with launching the server. It's basically stuff related to external JS, like: `Error: ENOENT: no such file or directory, open '/home/kuba/Projects/fakturama/tmp/source_map_concat-input_base_path-bThtEUaa.tmp/vendor/shims/md5.js'`. Is there any special way to get rid of those?

**Comment by lowski** [comment]
@qoobaa sorry, I haven't noticed that vendor directory was ignored.

I've added missing files. Could you check once again, please?

**Comment by qoobaa** [comment]
Now it works fine. Thank you!

**Pull request merged**
