### PR TITLE
Extract authentication from user model to dedicated service

### PR DESCRIPTION
**Pull request by lowski**
This refactoring was necessary to stub user's session in tests (previously session was coupled with user model which make it very difficult). I wanted to do that in order start writing tests to help regressions. I also added some acceptance test for clients and mirage for stubbing API requests.

I'm sorry that so many files have been changed but for some time I had "prettier" enabled in the editor and it automatically fixed files during edit. I think it makes sense to run prettier on the whole codebase (as a separate PR) to avoid it in the future.

I've also modified fix for removing invoices on submit (previous one was a quick fix).

@qoobaa please take a look into that when you have a moment.

### CODE REVIEW

**Comment by lowski** [comment]
If this gets merged I think it would be good to add some CI (i.e. Travis which is free for open source apps) to run our tests as part of PR process.

**Comment by qoobaa** [comment]
It's quite difficult to fully review due to lots of unrelated changes, but it looks fine in general. Here you go: https://travis-ci.org/qoobaa/fakturama.

Thank you for your effort, if you want to introduce more changes/refactoring. You're free to merge your PRs on your own if you need, Just let me know when you think I'm able to help somehow :-)

**Comment by lowski** [comment]
@qoobaa is it possible to deploy it to staging (I don't know how the process looks like). Do you mind doing some testing before we release it to production?

**Comment by lowski** [comment]
@qoobaa could you look at my previous question when you have a moment? Thanks!

**Comment by qoobaa** [comment]
Hey, sorry - I didn't notice your previous question.

Sure - it's possible to deploy it on staging to do some testing before deploying on production. Are you able to do it on your own (I believe you should have permissions to do so) or would you rather like me to deploy it for you?

**Comment by lowski** [comment]
@qoobaa how to deploy to staging? I suspect that `gh-pages` branch is used for production, right?

**Comment by qoobaa** [comment]
`ember build --environment staging && firebase deploy -e staging`
`ember build --environment production && firebase deploy -e production`

gh-pages is just a leftover I think - it's not hosted on GH pages any more. Let me know there are some issues with the commands above.

**Comment by lowski** [comment]
@qoobaa thanks for command, for deployment I had to use those (when I tried the once you provided I got error that `-e` option is not recognized): 

```
firebase use staging
firebase deploy
```

Do you mind checking it on staging? If it works for you, I would merge it and deploy.

**Comment by qoobaa** [comment]
The first issue that I see is:
image
It displays "Guest" when I'm logged in for some reason.

**Comment by lowski** [comment]
I was able to reproduce it but only reason for one of my emails. In that case firebase does not return email or displayName for the user (that's why it displays "Gość"). For another email it works fine.

@qoobaa Do you have an idea what might be wrong? I'm not able to reproduce it locally, the issue exists only on staging.

**Comment by lowski** [comment]
PS. Travos throws error because tests are failing from CLI - I need some time to take a look into that (when run with browser using `http://localhost:4200/tests` all pass).

**Comment by qoobaa** [comment]
I've imported the DB (users actually) in some weird way - that's possible cause. You don't need to care about it then.

**Comment by lowski** [comment]
> I've imported the DB (users actually) in some weird way - that's possible cause. You don't need to care about it then.

Ok so probably some of the emails are duplicated and since we have opt-in to prevent duplicates, we might see blank emails:

screenshot 2018-06-19 21 51 02

**Comment by lowski** [comment]
Travis has been fixed. @qoobaa are we good to merge it?

**Comment by qoobaa** [comment]
Sure!

**Pull request merged**
